service: opsaggregation
app: ops-aggregation
org: vfn2002

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  s3:
    port: 8000
    stage: dev
  reportWriteBucket: report-write-bucket
  reportReadBucket: report-read-bucket
  reportUnitBucket: report-unit-bucket

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: dev
  environment:
    REPORT_WRITE_BUCKET: ${self:custom.reportWriteBucket}
    REPORT_READ_BUCKET: ${self:custom.reportReadBucket}
    REPORT_UNIT_BUCKET: ${self:custom.reportUnitBucket}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

plugins:
  - serverless-webpack
  - serverless-s3-local
  - serverless-offline

functions:
  writeEvent:
    handler: ./src/event.writeEvent
    events:
      - http:
          path: write
          method: post
          cors: true

  buildReportingUnits:
    handler: ./src/jobs.buildReportingUnits
    events:
      - http:
          path: buildReportingUnits
          method: post
          cors: true

  aggregateDaily:
    handler: ./src/jobs.aggregateDaily
    events:
      - http:
          path: aggregateDaily
          method: post
          cors: true

  aggregateMonthly:
    handler: ./src/jobs.aggregateMonthly
    events:
      - http:
          path: aggregateMonthly
          method: post
          cors: true

  aggregateYearly:
    handler: ./src/jobs.aggregateYearly
    events:
      - http:
          path: aggregateYearly
          method: post
          cors: true

  getReport:
    handler: ./src/report.getReport
    events:
      - http:
          path: getReport
          method: get
          cors: true
          request:
            parameters:
              querystring:
                fromDate: true
                toDate: true
                tenant: true

resources:
  Resources:
    ReportWriteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.reportWriteBucket}
    ReportUnitBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.reportUnitBucket}
    ReportReadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.reportReadBucket}
